services:
  app:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: "${DATABASE_URL}"
      ARANGO_URL: "${ARANGO_URL}"
      ARANGO_DB: "${ARANGO_DB}"
      ARANGO_USER: "${ARANGO_USER}"
      ARANGO_PASSWORD: "${ARANGO_PASSWORD}"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL}"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entrypoints=websecure
      - traefik.http.services.${NAME}.loadbalancer.server.port=3000
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver

networks:
  web:
    external: true

